import os
import json
import time  # 👈 Added time module for the retry delay
from google import genai
from google.genai import types
from dotenv import load_dotenv

# Load environment variables from a .env file if present
load_dotenv()
client = genai.Client()

# Define the Synthesizer's Persona and Rules
synthesizer_persona = """
You are the Prompt Synthesizer for an autonomous multi-agent software factory.
Your job is to read a system architecture blueprint (JSON) and generate a highly specific, 
context-rich system prompt for a targeted developer agent.

You must extract ONLY the relevant schemas, API endpoints, and structural requirements 
for the requested target agent so they have perfect context without token waste.
"""

def generate_developer_prompt(blueprint_path: str, target_agent: str):
    # 1. Ensure the blueprint exists
    if not os.path.exists(blueprint_path):
        print(f"❌ Error: {blueprint_path} not found. Run architect.py first.")
        return

    # 2. Read the blueprint generated by the Architect
    with open(blueprint_path, "r") as f:
        blueprint_data = json.load(f)

    print(f"🧠 Synthesizer parsing blueprint for target: [{target_agent}]...")

    # 3. Construct the prompt for Gemini to synthesize the developer instructions
    user_content = f"""
    Based on the following system blueprint, generate a detailed system instruction prompt 
    for the '{target_agent}'. 
    
    Blueprint Context:
    {json.dumps(blueprint_data, indent=2)}
    
    The resulting prompt should clearly outline:
    - The exact files and components they need to build.
    - The API contracts they must consume or expose.
    - The data structures they need to respect.
    Do not write the application code itself; write the prompt that will command the developer agent.
    """

    # 👇 Added Retry Logic Here 👇
    max_retries = 3
    for attempt in range(max_retries):
        try:
            print(f"⏳ Calling Gemini API (Attempt {attempt + 1}/{max_retries})...")
            response = client.models.generate_content(
                model='gemini-3.5-flash',
                contents=user_content,
                config=types.GenerateContentConfig(
                    system_instruction=synthesizer_persona,
                    temperature=0.2,
                )
            )
            print("✅ Connection successful!")
            break  # If successful, break out of the retry loop
            
        except Exception as e:
            if "503" in str(e) or "UNAVAILABLE" in str(e) or "429" in str(e):
                if attempt < max_retries - 1:
                    print("⚠️ Servers are busy. Waiting 10 seconds before retrying...")
                    time.sleep(10)
                else:
                    print("❌ API is still busy after 3 attempts. Please try again later.")
                    return
            else:
                # If it's a different error, raise it immediately
                raise e

    # 4. Sanitize the filename to prevent OS file path errors
    clean_name = target_agent.lower().replace(' ', '_').replace('/', '_').replace('(', '').replace(')', '')
    output_filename = f"prompt_for_{clean_name}.txt"
    
    with open(output_filename, "w", encoding="utf-8") as f:
        f.write(response.text)

    print(f"📝 Autonomous prompt synthesized successfully and saved to: {output_filename}")
    print("\n--- Prompt Preview ---")
    print(response.text[:400] + "\n... [Truncated] ...")

# Change this line at the bottom of synthesizer.py:
if __name__ == "__main__":
    generate_developer_prompt("system_blueprint.json", "Enterprise Engineer (Java/Spring Boot)")